### ISSUE TITLE
How to make a gap between two damage_effect?

### ISSUE THREAD

**Issue by CutUpTheEastWind** [guladam/deck_builder_tutorial#29] opened 2024-09-29 20:28 UTC
func apply_effects(targets: Array[Node], modifiers: ModifierHandler) -> void:
		var damage_effect := DamageEffect.new()
		damage_effect.amount = modifiers.get_modified_value(base_damage, Modifier.Type.DMG_DEALT_PLUS)
		damage_effect.amount = modifiers.get_modified_value(damage_effect.amount, Modifier.Type.DMG_DEALT_PERCENT)
		damage_effect.sound = sound
		damage_effect.execute(targets)
		damage_effect.execute(targets)

I make a double_strike card with this kind of func apply_effects, and try to make a gap like 0.2s between the two damage_effect. But I find it's seems hard to me. I thought a way by make a TimerHandler under the Battle scene and pass the targets and damage_effect to it to let it handle the second damage_effect. I think it's a bad way to solve this, any better way?

**Comment by guladam** [comment] 2024-09-30 05:39
Hey, 

We already did this for the bat enemy, with tweens:

https://github.com/guladam/deck_builder_tutorial/blob/main/enemies/bat/bat_attack_action.gd

You can use a similar approach. I close this for now as this is clearly not a bug with the project. Please keep the issues for bugs in the future!

**Closed as completed by guladam** 2024-09-30 05:39 UTC

**Comment by CutUpTheEastWind** [comment] 2024-09-30 11:02
> Hey,
> 
> We already did this for the bat enemy, with tweens:
> 
> https://github.com/guladam/deck_builder_tutorial/blob/main/enemies/bat/bat_attack_action.gd
> 
> You can use a similar approach. I close this for now as this is clearly not a bug with the project. Please keep the issues for bugs in the future!

Actually it's not quite same, bat_attack_action is extents from Node, but the card is extents from Resourse and can't create_tween, that make me feel confuse. Should I change the extents to solve this?

**Comment by CutUpTheEastWind** [comment] 2024-09-30 11:04
get_tree and create Timer also can't work, that's why I really hope to get a method.

**Comment by guladam** [comment] 2024-09-30 11:11
Yes you're right about that. Resources exist outside the SceneTree so you can't access those things.

However, if you have at least one valid target, that's a node, so all of those things are accessible.

target[0].get_tree().create_tween() and you're good to go :)

**Comment by CutUpTheEastWind** [comment] 2024-09-30 13:34
> Yes you're right about that. Resources exist outside the SceneTree so you can't access those things.
> 
> However, if you have at least one valid target, that's a node, so all of those things are accessible.
> 
> target[0].get_tree().create_tween() and you're good to go :)

Thanks for your patient, it works well now. Sorry to use issue page for questioning, I'm very new in game development and your video really helpful to me, it make me much more understand how the game works. I plan to learn the auto chess class later, thanks again!

Good luck
