### ISSUE TITLE
How To make Idle animation for player and enemy ?

### ISSUE THREAD

**Issue by Zifai** [guladam/deck_builder_tutorial#7] opened 2024-04-25 18:51 UTC
i Confused to make Idle animation for card , player or enemy ? sprite sheet or multiple sprite maybe green screen video.

**Comment by BrokedArrer** [comment] 2024-06-16 15:55
If you wanted to animate the sprites of the enemies and the character you simply need to add an animated sprite, or animation player. You can do this by removing the Sprite for example in the Player.tscn, replacing it with an animated sprite2d, setting it to auto play the animation, and then updating the code where you reference the Sprite, to Sprite2D.

**Comment by guladam** [comment] 2024-06-25 07:11
if you don't mind it, I close this for now as this is not a bug but an additional feature

**Closed as completed by guladam** 2024-06-25 07:11 UTC
